name: Push Event workflow file
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: my file
        run: echo "hello world"
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: my file
        run: echo "hello world"
   
